todo_app/urls.py
from django.urls import path, include
from .views import (
    TaskList,
    TaskDetail,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    CustomLoginView,
    RegisterPage,
    TaskReorder,
)
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
    path("", TaskList.as_view(), name="tasks"),
    path("task/<uuid:pk>/", TaskDetail.as_view(), name="task_detail"),
    path("task-create/", TaskCreate.as_view(), name="task-create"),
    path("task-update/<uuid:pk>/", TaskUpdate.as_view(), name="task_update"),
    path("task-delete/<uuid:pk>/", TaskDelete.as_view(), name="task_delete"),
    path("task-reorder/", TaskReorder.as_view(), name="task-reorder"),
]

todo_pro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls")),
]

todo_app/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
import datetime as dt


# Create your models here.


class Task(models.Model):
    id = models.UUIDField(
        primary_key=True,
        null=False,
        unique=True,
        default=uuid.uuid4,
        editable=False,
    )
    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="users_task",
    )
    task_title = models.CharField(
        max_length=100,
        null=False,
    )
    task_description = models.TextField(
        max_length=300,
        null=True,
        blank=True,
    )
    is_important = models.BooleanField(
        default=False,
    )
    task_completed = models.BooleanField(
        default=False,
    )
    task_created_at = models.DateTimeField(
        auto_now_add=True,
    )
    task_updated_at = models.DateTimeField(
        auto_now=True,
    )
    task_due_date = models.DateTimeField(
        default=dt.datetime.now() + dt.timedelta(days=1),
    )

    def __str__(self) -> str:
        return str(self.task_title)

    def save(self, *args, **kwargs):
        if self.task_due_date is None:
            self.task_due_date = dt.datetime.now() + dt.timedelta(days=1)
        super(Task, self).save(*args, **kwargs)

todo_app/forms.py
from django import forms

# Reordering Form and View


class PositionForm(forms.Form):
    position = forms.CharField()

todo_app/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from .models import Task

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.

from django.views import View
from django.shortcuts import redirect
from django.db import transaction
from .forms import PositionForm

# def task_list(request):
#     return HttpResponse("this is taks list")


class CustomLoginView(LoginView):
    template_name = "todo_app/login.html"
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self) -> str:
        return reverse_lazy("tasks")


class RegisterPage(FormView):
    template_name = "todo_app/register.html"
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("tasks")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args: str, **kwargs: Any):
        if self.request.user.is_authenticated:
            return redirect("tasks")
        return super(RegisterPage, self).get(*args, **kwargs)


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["tasks"] = context["tasks"].filter(user_id=self.request.user)
        context["count"] = context["tasks"].filter(task_completed=False).count()

        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = "task_detail"


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = [
        "task_title",
        "task_description",
        "is_important",
        "task_completed",
        "task_due_date",
    ]
    success_url = reverse_lazy("tasks")

    def form_valid(self, form):
        form.instance.user_id = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = [
        "task_title",
        "task_description",
        "is_important",
        "task_completed",
        "task_due_date",
    ]
    success_url = reverse_lazy("tasks")


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "tasks"
    success_url = reverse_lazy("tasks")


class TaskReorder(View):
    def post(self, request):
        form = PositionForm(request.POST)

        if form.is_valid():
            positionList = form.cleaned_data["position"].split(",")

            with transaction.atomic():
                self.request.user.set_task_order(positionList)

        return redirect(reverse_lazy("tasks"))

templates/todo_app/login.html
{% extends 'todo_app/main.html' %}
{% block content %}

<style>
    body {
        background-color: #f9f9f9;
        font-family: 'Nunito', sans-serif;
    }

    .container {
        max-width: 400px;
        margin: auto;
        background-color: #fff;
        border-radius: 10px;
        padding: 30px;
        box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        color: #EB796F;
        margin-bottom: 20px;
    }

    form {
        display: flex;
        flex-direction: column;
    }

    input[type='text'],
    input[type='password'] {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 15px;
        font-size: 16px;
    }

    input[type='submit'] {
        border: none;
        background-color: #EB796F;
        color: #fff;
        font-size: 18px;
        font-weight: 600;
        padding: 12px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type='submit']:hover {
        background-color: #D45A49;
    }

    p {
        text-align: center;
        margin-top: 20px;
    }

    p a {
        color: #EB796F;
        text-decoration: none;
    }

    p a:hover {
        text-decoration: underline;
    }

</style>

<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <input type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
</div>

{% endblock content %}

templates/todo_app/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="This is to do list implemented using Django by Dennis Ivy who is a full stack web developer.">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>To Do Items</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>


    <style>
        body {
            background-color: #FAFAFA;
            font-family: 'Nunito', sans-serif;
            padding-top: 50px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: 'Raleway', sans-serif;
        }

        a,
        p {
            color: #4b5156;
        }

        a {
            font-weight: 600;
        }

        .container {
            max-width: 550px;
            margin: auto;
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
            animation: fadeIn 1s;
        }

        input {
            outline: none;
            border: none;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #FFC947 0%, #FF7373 43%, #FF7373 100%);
            animation: fadeIn 1s;
        }

        .header-bar a {
            color: #fff;
            text-decoration: none;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
            overflow: hidden;
            animation: slideInUp 0.5s;
        }

        .task-title {
            display: flex;
            padding: 20px;
            align-items: center;
            gap: 10px;
            width: 100%;
        }

        .task-title a {
            text-decoration: none;
            color: #4b5156;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: #66D395;
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: #D6D6D6;
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #F67280;
            font-size: 22px;
            line-height: 0;
            padding: 20px 20px;
        }

        /*Handle Classes*/

        .handle {
            display: inline-block;
            padding: 20px 16px;
            cursor: grab;
            user-select: none;
        }

        .handle:after,
        .handle:before {
            display: block;
            content: "";
        }

        .handle:active,
        .handle:active:before,
        .handle:active:after {
            cursor: grabbing;
        }

        .dropArea {
            background-color: #F1F2F6;
            color: black;
            border: #CED6E0 1px solid;
        }

        .selectedTask {
            opacity: 0.6;
        }

        #add-link {
            color: #FF7373;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }

        @media screen and (max-width: 320px) {
            #search-add-wrapper {
                padding: 10px;
            }
        }

        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
            background-color: #F5F5F5;
        }

        label {
            padding-top: 10px !important;
            display: block;
            font-weight: bold;
            color: #4b5156;
        }

        ::placeholder {
            font-weight: 300;
            opacity: 0.5;
        }

        input[type=checkbox] {
            appearance: none;
            width: 20px;
            height: 20px;
            border: 2px solid #FF7373;
            border-radius: 3px;
            outline: none;
            cursor: pointer;
            position: relative;
            margin-right: 5px;
        }

        input[type=checkbox]:before {
            content: '';
            display: block;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) scale(0);
            width: 10px;
            height: 10px;
            background-color: #FF7373;
            border-radius: 2px;
            opacity: 0;
        }

        input[type=checkbox]:checked:before {
            content: '\2713'; /* Unicode for tick symbol */
            font-size: 14px;
            color: #fff;
            text-align: center;
            line-height: 16px;
            transform: translate(-50%, -50%) scale(1);
            opacity: 1;
        }

        input[type=submit] {
            border: none;
            background-color: #FF7373;
            color: #fff;
            font-size: 16px;
            font-weight: 600;
            padding: 10px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 20px;
            transition: background-color 0.3s ease;
        }

        input[type=submit]:hover {
            background-color: #F67280;
        }

        /* Error styling for form fields */
        .error {
            color: #ff3d3d;
            margin-top: 5px;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        @keyframes slideInUp {
            from {
                transform: translateY(100%);
            }
            to {
                transform: translateY(0);
            }
        }
    </style>
</head>

<body>

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

</body>

</html>

templates/todo_app/register.html
{% extends 'todo_app/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
</div>




{% endblock content %}

templates/todo_app/task_confirm_delete.html
{% extends 'todo_app/main.html' %}
{% block content %}

<style>
    body {
        background-color: #F6F9FC;
        font-family: 'Nunito', sans-serif;
    }

    .container {
        max-width: 550px;
        margin: auto;
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
    }

    a {
        color: #EB796F;
        text-decoration: none;
        font-size: 18px;
        margin-bottom: 20px;
    }

    p {
        font-size: 18px;
        color: #4b5156;
        margin-bottom: 20px;
    }

    form {
        display: flex;
        flex-direction: column;
    }

    input[type='submit'] {
        border: none;
        background-color: #EB796F;
        color: #fff;
        font-size: 16px;
        font-weight: 600;
        padding: 10px;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 20px;
        transition: background-color 0.3s ease;
    }

    input[type='submit']:hover {
        background-color: #D45A49;
    }

    /* Beautiful button animation */
    @keyframes animateButton {
        0% {
            transform: scale(1);
        }

        50% {
            transform: scale(1.1);
        }

        100% {
            transform: scale(1);
        }
    }

    .animate-on-click {
        animation: animateButton 0.3s ease;
    }

</style>

<div class="container">
    <a href="{% url 'tasks' %}">Go Back</a>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete this task? {{ task }}</p>
        <input type="submit" value="Delete" class="animate-on-click">
    </form>
</div>

{% endblock content %}

templates/todo_app/task_detail.html
{% extends 'todo_app/main.html' %}
{% block content %}
<h1> Task: {{task_detail}} </h1>
{% endblock content %}

templates/todo_app/task_form.html
{% extends 'todo_app/main.html' %}
{% block content %}

<style>
    body {
        background-color: #F6F9FC;
        font-family: 'Nunito', sans-serif;
    }

    .container {
        max-width: 550px;
        margin: auto;
        background-color: #fff;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
    }

    h3 {
        margin-top: 0;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
    }

    a {
        color: #EB796F;
        text-decoration: none;
        font-size: 18px;
    }

    form {
        margin-top: 20px;
        display: flex;
        flex-direction: column;
    }

    label {
        font-weight: 600;
        margin-top: 10px;
    }

    input[type='text'],
    textarea {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 10px;
        font-size: 16px;
        margin-top: 5px;
        width: 100%;
    }

    textarea {
        resize: vertical;
        min-height: 100px;
    }

    /* Styling for checkboxes */
    #id_is_important {
        display: flex;
        align-items: center;
        margin-top: 10px;
        margin-right: 5px;
        appearance: none;
        width: 20px;
        height: 20px;
        border: 2px solid #EB796F;
        border-radius: 3px;
        outline: none;
        cursor: pointer;
        position: relative;
        background-color: #fff; /* Add a background color for the checkbox */
    }

    #id_is_important:before {
        content: '';
        display: block;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0);
        width: 10px;
        height: 10px;
        background-color: #EB796F;
        border-radius: 2px;
        opacity: 0;
    }

    #id_is_important:checked:before {
        content: '\2713'; /* Unicode for tick symbol */
        font-size: 14px;
        color: #fff;
        text-align: center;
        line-height: 16px;
        transform: translate(-50%, -50%) scale(1);
        opacity: 1;
    }
    #id_is_important:checked {
        background-color: #EB796F;
        border-color: #EB796F;
    }

    /* Style the checked state for better visibility */
    #id_task_completed:checked {
        background-color: #EB796F;
        border-color: #EB796F;
    }
        #id_task_completed {
        display: flex;
        align-items: center;
        margin-top: 10px;
        margin-right: 5px;
        appearance: none;
        width: 20px;
        height: 20px;
        border: 2px solid #EB796F;
        border-radius: 3px;
        outline: none;
        cursor: pointer;
        position: relative;
        background-color: #fff; /* Add a background color for the checkbox */
    }

    #id_task_completed:before {
        content: '';
        display: block;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) scale(0);
        width: 10px;
        height: 10px;
        background-color: #EB796F;
        border-radius: 2px;
        opacity: 0;
    }

    #id_task_completed:checked:before {
        content: '\2713'; /* Unicode for tick symbol */
        font-size: 14px;
        color: #fff;
        text-align: center;
        line-height: 16px;
        transform: translate(-50%, -50%) scale(1);
        opacity: 1;
    }

    /* Style the checked state for better visibility */
    #id_task_completed:checked {
        background-color: #EB796F;
        border-color: #EB796F;
    }

    input[type='submit'] {
        border: none;
        background-color: #EB796F;
        color: #fff;
        font-size: 16px;
        font-weight: 600;
        padding: 10px;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 20px;
        transition: background-color 0.3s ease;
    }

    input[type='submit']:hover {
        background-color: #D45A49;
    }

    .flatpickr-calendar {
        box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        border-radius: 5px;
        font-family: 'Nunito', sans-serif;
        z-index: 9999; /* Increase z-index to make sure it appears above other elements */
    }

    .flatpickr-days {
        background-color: #F6F9FC;
    }

    .flatpickr-days .flatpickr-day {
        color: #4b5156;
    }

    .flatpickr-day:hover,
    .flatpickr-day.selected,
    .flatpickr-day.selected.inRange,
    .flatpickr-day.startRange,
    .flatpickr-day.endRange {
        background-color: #EB796F;
        color: #fff;
    }

    .flatpickr-time {
        background-color: #fff;
    }

    .flatpickr-time input {
        border: 1px solid #ced4da;
        border-radius: 5px;
        padding: 10px;
        font-size: 16px;
        margin-top: 5px;
        width: 100%;
    }

    .flatpickr-confirm {
        color: #EB796F;
        font-weight: 600;
        cursor: pointer;
    }

    .flatpickr-confirm:hover {
        background-color: #D45A49;
        color: #fff;
    }



</style>

<div class="container">
    <h3>Task Form</h3>
    <a href="{% url 'tasks' %}">GO BACK</a>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    const currentDate = new Date(); // Get the current date and time

    flatpickr('#id_task_due_date', {
        enableTime: true,
        dateFormat: 'Y-m-d H:i',
        minDate: currentDate, // Set the minimum date and time to the present
        // You can add more options here as per your requirements
    });
</script>

{% endblock content %}

templates/todo_app/task_list.html
{% extends 'todo_app/main.html' %}
{% block content %}
<style>
    /* Style for the datetime section */
body {
  font-family: Arial, sans-serif;
  line-height: 1.6;
  background-color: #f9f9f9;
  margin: 0;
  padding: 0;
}

/* Container style */
.container {
  max-width: 960px;
  margin: 0 auto;
  padding: 20px;
}

/* Style for the datetime section */
#datetime {
  margin-bottom: 20px;
  font-size: 18px;
  color: #4b5156;
}

/* Style for the task date header */
h3 {
  font-size: 18px;
  margin-bottom: 10px;
  color: #333;
  border-bottom: 1px solid #ddd;
  padding-bottom: 5px;
}

/* Style for the task items wrapper */
.task-items-wrapper {
  max-height: 700px;
  overflow-y: auto;
  padding-right: 10px;
}

/* Responsive styles for task items */
@media (max-width: 768px) {
  .task-items-wrapper {
    max-height: none;
    overflow-y: visible;
    padding-right: 0;
  }
}
    .task-items-wrapper {
        max-height: 700px; /* Set a maximum height for the task list */
        overflow-y: auto; /* Add vertical scrollbar if content exceeds the maximum height */
        padding-right: 10px; /* Add some padding to the right to ensure scrollbar visibility */
    }

    /* Responsive styles for task items */
    @media (max-width: 768px) {
        .task-items-wrapper {
            max-height: none; /* Remove the maximum height for smaller screens */
            overflow-y: visible; /* Show all content on smaller screens */
            padding-right: 0; /* Remove the padding on smaller screens */
        }
    }

.task-controls {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 10px;
}

/* Style for the description button */
.description-button {
  background-color: #007bff;
  color: white;
  padding: 8px 20px;
  cursor: pointer;
  border: none;
  border-radius: 25px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
}

.description-button:hover {
  background-color: #0056b3;
  transform: scale(1.05);
}

/* Style for the delete link */
.delete-link {
  background-color: #dc3545;
  color: white;
  padding: 15px;
  margin:30px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  transition: background-color 0.2s ease-in-out, transform 0.2s ease-in-out;
}

.delete-link:hover {
  background-color: #c82333;
  transform: translateY(-2px);
}

.delete-link:active {
  background-color: #bd2130;
  transform: translateY(0);
}

/* Style for the delete icon */
.delete-icon {
  width: 18px;
  height: 18px;
  background-color: #fff;
  display: inline-block;
  margin-right: 5px;
}

/* Additional style for the task description */
.task-description p {
  margin-bottom: 0;
}

/* Updated style for task wrapper */

/* Style for the task controls on hover */
.task-wrapper:hover .task-controls {
  opacity: 1;
  transform: translateY(-5px);
}

/* Style for the task controls on active */
.task-wrapper.active .task-controls {
  opacity: 1;
  transform: translateY(-5px);
}

/* Style for the task wrapper */
.task-wrapper {
position: relative;
  border-radius: 5px;
  border: 1px solid #ddd;
  padding: 10px;
  margin-bottom: 10px;
  background-color: #fff;
  transition: border-color 0.2s ease-in-out, transform 0.2s ease-in-out;
}

.task-wrapper:hover {
  border-color: #007bff;
  transform: translateY(-2px);
}

/* Style for completed tasks */
.task-wrapper.completed {
  background-color: #f0f0f0;
}

/* Style for task icons */
.task-icon {
  width: 24px;
  height: 24px;
  margin-right: 5px;
  display: inline-block;
}

/* Task incomplete icon */
.task-incomplete-icon {
  background-color: #ffcc00;
}

/* Task complete icon */
.task-complete-icon {
  background-color: #4caf50;
}

/* Style for task title link */
.task-title a {
  color: #007bff;
  text-decoration: none;
}

.task-title a:hover {
  text-decoration: underline;
}

.task-description {
  display: none;
  margin-top: 10px;
  padding: 10px;
  border-radius: 5px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  transition: opacity 0.2s ease-in-out;
  background-color: #ffffff; /* Update background color to white */
}

.task-wrapper.active .task-description {
  display: block;
  animation: fadeIn 0.3s ease-in-out;
}






</style>

<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a> {% else %}
    <a href="{% url 'login' %}">Login</a> {% endif %}
</div>

<div id="tasklist" class="task-items-wrapper">
    <!-- ... Your existing task listing ... -->
    {% if tasks|length > 0 %}
    <a id="add-link" href="{% url 'task-create' %}">&#x2b;</a>
    <b><div id="datetime"></div></b>
    <hr>
    {% endif %}

    {% with current_date="" %}
    {% for task in tasks|dictsort:"task_due_date" %}
    <!-- The "dictsort" filter is used to sort tasks based on their "task_due_date" -->
    {% if task.task_due_date != current_date %}
    {% if not forloop.first %}
    </div>
    {% endif %}
    <h3>{{ task.task_due_date|date:"F j, Y" }}</h3>
    <div>
    {% endif %}
    <div class="task-wrapper">
        <div class="task-title">
            {% if task.task_completed %}
            <div class="task-complete-icon"></div>
            <i><s><a href="{% url 'task_update' task.id %}">{{task}}</a></s></i>
            {% else %}
            <div class="task-incomplete-icon"></div>
            <a href="{% url 'task_update' task.id %}">{{task}}</a>
            {% endif %}
        </div>
        <div class="task-controls">
            <a class="delete-link" href="{% url 'task_delete' task.id %}">&#215;</a>
            <button class="description-button" onclick="toggleTaskDescription(this)">View Description</button>

        </div>
        <div class="task-description">
            {{ task.task_description }}
        </div>
    </div>
    {% with current_date=task.task_due_date %}
    {% endwith %}
    {% endfor %}
    </div>
    {% endwith %}
</div>

<form style="display: none;" id="reorderForm" method="post" action="{% url 'task-reorder' %}">
    {% csrf_token %}
    <input type="hidden" id="positionInput" name="position">
</form>

<script>
    var taskList = document.getElementById("tasklist");
    var reorderForm = document.getElementById("reorderForm");
    var positionInput = document.getElementById("positionInput");

    let sortable = Sortable.create(taskList, {
        handle: '.handle',
        ghostClass: 'dropArea',
        chosenClass: 'selectedTask',
    });

    // Function to show/hide task description on button click
    function toggleTaskDescription(button) {
        const taskWrapper = button.parentElement.parentElement;
        const description = taskWrapper.querySelector(".task-description");
        taskWrapper.classList.toggle("active");
        description.style.display = (description.style.display === "block") ? "none" : "block";
    }

    function reordering() {
        const rows = document.getElementsByClassName("task-wrapper");
        let pos = [];
        for (let row of rows) {
            pos.push(row.dataset.position);
        }
        console.log(pos.join(","))
        positionInput.value = pos.join(',');
        reorderForm.submit();
    }

    document.ondrop = reordering;

    function updateDateTime() {
        const datetimeDiv = document.getElementById("datetime");
        const currentDate = new Date();
        const formattedDate = currentDate.toLocaleDateString();
        const formattedTime = currentDate.toLocaleTimeString();
        datetimeDiv.innerHTML = `Today's Date: ${formattedDate} | Current Time: ${formattedTime}`;
    }

    // Update date and time every second
    setInterval(updateDateTime, 1000);
    updateDateTime(); // Call immediately to set initial value
</script>

{% endblock content %}